### PR TITLE
Test, clean up archive/CleanFilePath, getStrategy

### PR DESCRIPTION
**Pull request by 200sc**
This is a simple changeset removing an excess `filepath.ToSlash` call from `archive.CleanFileName`, also bringing over tests from the stdlib `filepath` package to verify no change happened in that removal.

It also adds tests for archive.getStrategy, and uses a map for archive strategy strings.

### CODE REVIEW

**Comment by fasterthanlime** [comment]
:+1: LGTM, merged! Thanks for the contributions :)

**Comment by fasterthanlime** [comment]
I'm seeing some test failures on Linux & macOS, maybe that `ToSlash` wasn't unnecessary after all :)

**Comment by 200sc** [comment]
Perhaps, I tested on windows.

**Comment by fasterthanlime** [comment]
I pushed a version that doesn't rely on `path/filepath` at all, so we get behavior that's consistent across platforms 🌟

**Pull request merged**
